# Generated by Django 3.2.15 on 2022-09-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(blank=True, null=True, verbose_name='ID объекта в Google sheet')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='ID заказа')),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость в USD')),
                ('price_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Стоимость в рублях')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Срок поставки')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чек',
            },
        ),
    ]
