version: "3.9"

services:
  db:
    image: postgres:13-alpine
    container_name: google_sheets_db
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql
    restart: always
    ports:
      - '5432:5432'

  web:
    container_name: google_sheets
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pg_data: